### ISSUE TITLE
Missing peerDependency react-dom

### ISSUE THREAD

**Issue by slydor** [react-grid-layout/react-resizable#245]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x] Bug
- [ ] Feature Request
- [ ] Question

### Problem Report

`react-resizable` depends on `react-draggable` and that defines [peerDependencies](https://github.com/react-grid-layout/react-draggable/blob/master/package.json#L99) of `react` and `react-dom`.
As far as I know, for technical correctness this peer needs to be elevated up as well.

In our project we use `react-grid-layout@1.4.4` and `yarn@3.6.4`. Of course, we have `react-dom` installed on the same project.

After `yarn install` it complains about that missing peer with:

```shell
➤ YN0002: │ react-resizable@npm:3.0.5 [065e4] doesn't provide react-dom (pd89a4), requested by react-draggable
```

And it is hotfixable by adding this to the `.yarnrc.yml` file:

```yaml
packageExtensions:
  # Prevent the warning by overriding the required peer. We just took the same version as defined in react-draggable
  'react-resizable@3.0.5':
    peerDependencies:
      'react-dom': '>= 16.3.0'
```

#### System Info

Node Version: 20.17.0
Browser: none
OS: Ubuntu 22.04

#### Reproduction

I reproduced it with `yarn@4`, but we see the same issue: https://github.com/slydor/react-resizable-missing-react-dom-peer
